### PR TITLE
fix(ui5-label): use correct i18n bundle & make component language aware

### PR DESCRIPTION
**Pull request by Lukas742**

### CODE REVIEW

**Review by nnaydenow — APPROVED** [review]
@gmkv fyi

**Comment by 0anton** [comment]
Which release this fix managed to get in?
It is anounced for `v1.18.1-rc.0` pre-release but not mentioned in release `v1.19.0`.
We are facing performance problems in the app due to 1000 warnings about labels missing i18n table.

**Comment by Lukas742** [comment]
Hi @0anton 

this was also fixed in `v1.19.0` even though it doesn't show up in the release log for that version. 
@ilhan007 do you know why this change was omitted in the release log?

**Comment by ilhan007** [comment]
Hi @Lukas742 an issue with the change log generation process, sorry for the confusion @0anton

**Pull request merged**
