### PR TITLE
refactor(ui5-badge): change default values of properties

### PR DESCRIPTION
**Pull request by kskondov**
Changes the default value of the ```design``` property

BREAKING CHANGE: 
The ```design``` property has new default value ```Neutral``` instead of ```Set3```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461

### CODE REVIEW

**Review by ilhan007 — CHANGES_REQUESTED** [review]
Should not you also update the default styles when no attribute is provided to match the default design

**Review by dimovpetar — CHANGES_REQUESTED** [review]
Also check the samples under "packages/website/docs/_samples/main/Badge/...". Make sure that those badges that use `color-scheme` also have `design` set.

**Review by TeodorTaushanov — CHANGES_REQUESTED** [review]
Let's keep colorScheme=1 as a default value.

For design="Set3" 7 is the correct default value, but for Set1 and Set2 it is not.

**Review by TeodorTaushanov — APPROVED** [review]

**Review by dimovpetar — CHANGES_REQUESTED** [review]
Changes to Badge functionality look good, but [docusaurus.config.ts](https://github.com/SAP/ui5-webcomponents/pull/8601/files#diff-05b21b47e3c534d46dc50ec43ac6a51c829f7b2bcf5c6cc21e99587704bcf54f) seems like a rebasing issue

**Review by dimovpetar — APPROVED** [review]

**Comment by kskondov** [comment]
> Should not you also update the default styles when no attribute is provided to match the default design

Done

**Review by dimovpetar — APPROVED** [review]

**Comment by kskondov** [comment]
> Should not you also update the default styles when no attribute is provided to match the default design

Done

**Pull request merged**
