### PR TITLE
fix(ui5-avatar): avatar initials correct display

### PR DESCRIPTION
**Pull request by PetyaMarkovaBogdanova**
Fixes: #6585
Fixes: #6516

### CODE REVIEW

**Review by yanaminkova — APPROVED** [review]

**Review by nnaydenow — CHANGES_REQUESTED** [review]
Change PR title to be ui5-avatar related. Testing it locally the change doesn't work as expected. If fallback icon is set initials container `avatar.querySelector(".ui5-avatar-initials")` return null and the expression is never done.

**Comment by PetyaMarkovaBogdanova** [comment]
> Change PR title to be ui5-avatar related. Testing it locally the change doesn't work as expected. If fallback icon is set initials container `avatar.querySelector(".ui5-avatar-initials")` return null and the expression is never done.

In what case did you see the fallback icon being set?

**Comment by nnaydenow** [comment]
> > Change PR title to be ui5-avatar related. Testing it locally the change doesn't work as expected. If fallback icon is set initials container `avatar.querySelector(".ui5-avatar-initials")` return null and the expression is never done.
> 
> In what case did you see the fallback icon being set?

Using the initial from the original issue "RHB". If you change the initials to "RH" for example the fallback icon will not be removed as expected.

**Comment by PetyaMarkovaBogdanova** [comment]
@nnaydenow , can you, please, check my new solution?

**Comment by nnaydenow** [comment]
1. In main initials are with lower priority than icon (if icon attribute exist => show icon). Currently if initials are set the icon will not appear.
2. In main if invalid initials are used the fallback icon is shown. Currently if we set for example `ЦИ` empty avatar will appear.
3. Resize handler is not called if the avatar is defined as and initials are set on a later stage: 
```html
<ui5-avatar id="test" size="XS" icon="share"></ui5-avatar>
<script>
	const test = document.getElementById("test");
	setTimeout(() => test.initials = "AC", 3000);
</script>
```

**Review by nnaydenow — CHANGES_REQUESTED** [review]
```html
<ui5-avatar initials="RHB" size="XS"></ui5-avatar>
```
resolves to:
```html
<ui5-avatar initials="RHB" size="XS" icon="employee"></ui5-avatar>
```

With this setup icon can't be removed.



https://user-images.githubusercontent.com/31909318/230563275-1a8a951a-6ba7-4e73-9f31-3359729ddd3c.mov


https://user-images.githubusercontent.com/31909318/230565019-8fada5fc-68f9-4a01-bd1a-d21fbb8b257e.mov

**Comment by PetyaMarkovaBogdanova** [comment]
@nnaydenow I experienced the same issue, but it seemed unlogical compared to the new code, so I rebuild and reloaded WC project. Can you, please, try doing that and test again, the issue is not happening on my side.

**Comment by nnaydenow** [comment]
> @nnaydenow I experienced the same issue, but it seemed unlogical compared to the new code, so I rebuild and reloaded WC project. Can you, please, try doing that and test again, the issue is not happening on my side.

Seems like I haven't rebased successfully. Works okey for me.

**Review by yanaminkova — APPROVED** [review]

**Pull request merged**
