### PR TITLE
feat(ui5-li-notification): adjust focus styles to sap_horizon

### PR DESCRIPTION
**Pull request by GerganaKremenska**

### CODE REVIEW

**Review by alexandar-mitsev — CHANGES_REQUESTED** [review]
- on http://localhost:8081/test-resources/pages/NotificationListItem.html the bottom border of the header of the list makes the rounded corners look broken. Either remove it or do not round the corners if there is a header
- rounded corners look broken when in NotificationListGroup

**Comment by GerganaKremenska** [comment]
> * on http://localhost:8081/test-resources/pages/NotificationListItem.html the bottom border of the header of the list makes the rounded corners look broken. Either remove it or do not round the corners if there is a header
> * rounded corners look broken when in NotificationListGroup

* Removed header, because border can not be removed, this is a good feedback for designers.
* NotificaitonListGroup is not with rounded coreners as in openui5

**Comment by alexandar-mitsev** [comment]
> > * on http://localhost:8081/test-resources/pages/NotificationListItem.html the bottom border of the header of the list makes the rounded corners look broken. Either remove it or do not round the corners if there is a header
> > * rounded corners look broken when in NotificationListGroup
> 
> * Removed header, because border can not be removed, this is a good feedback for designers.
> * NotificaitonListGroup is not with rounded coreners as in openui5

* removing the header fixes it for the second sample, but the first one is still broken. can you make the round corners only if there is no header? If it is not easy - we can leave it like it is

**Review by TeodorTaushanov — APPROVED** [review]

**Comment by GerganaKremenska** [comment]
> > > * on http://localhost:8081/test-resources/pages/NotificationListItem.html the bottom border of the header of the list makes the rounded corners look broken. Either remove it or do not round the corners if there is a header
> > > * rounded corners look broken when in NotificationListGroup
> > 
> > 
> > 
> > * Removed header, because border can not be removed, this is a good feedback for designers.
> > * NotificaitonListGroup is not with rounded coreners as in openui5
> 
> * removing the header fixes it for the second sample, but the first one is still broken. can you make the round corners only if there is no header? If it is not easy - we can leave it like it is

This is coming from the list an we can not overwrite it. We should leave it for the next steps and contact the list colleagues

**Review by alexandar-mitsev — APPROVED** [review]

**Pull request merged**
