### PR TITLE
feat(ui5-date-picker): component is now aligned with the specification

### LINKED ISSUE #2151: DatePicker enhacements - part 1
- [ ] When there is no selected date, the current month and year should not be selected, but only focused.
- [ ] When month/year is selected, the focus should remain on the same day (date) of the selected month.
- [ ] When year picker is opened, the selected year should be focused and located in the center(third column, third row)

### PR DESCRIPTION
**Pull request by unazko**
Focus handling is aligned with the KBH specification:
- When an year is selected from the year picker the day picker is shown and focus
is set to the last selected date or to the current date.
- When a month is selected from the month picker the day picker is shown and focus
is set to the last selected date or to the current date.
- When month picker is opened the focus is set to the selected month or to the current month
if there are no selected dates.
- When year picker is opened the focus is set to the selected year or to the current year
if there are no selected dates.

Selection is applied in compliance with the UX specification, when a picker is opened:
- Calendar items from the month picker and year picker are not rendered selected, when there are no
selected dates.

Fixes #2151

### CODE REVIEW

**Comment by ilhan007** [comment]
@unazko could you merge the master, as there have been changes to the ui5-date-picker by your team
and I suppose your PR is related to this issue: https://github.com/SAP/ui5-webcomponents/issues/2151
Could you please reference it in the commit body?

**Comment by unazko** [comment]
There is still one issue left with the focus placement after a month or year is chosen.

**Comment by tsanislavgatev** [comment]
Looks good to me. But you have merge conflict @unazko

**Comment by unazko** [comment]
After a discussion with Vladislav I understood that the two additional tests need to be changed, in order to more stable and not introduce timing issues into the whole test set.

**Comment by tsanislavgatev** [comment]
Looks good to me. @ilhan007 @fifoosid

**Review by ilhan007 — APPROVED** [review]

**Pull request merged**
