### PR TITLE
fix(ui5-menu): restore focus to the opener

### PR DESCRIPTION
**Pull request by unazko**
- The focus is restored over the opener element after root menu close.
- Redundant icon dependency is removed from the menu.
- Escape keyboard key press closes all dialogs on mobile device.
- Sub-menu could not be opened from a disabled `ui5-menu-item`.
- The leftover `start-section` property usage is replaced with the `ui5-menu-separator` component usage.

Fixes: #9317

### CODE REVIEW

**Review by TeodorTaushanov — APPROVED** [review]

**Comment by unazko** [comment]
The `prevent-focus-restore` attribute is now remove from the menu template as discussed with @TeodorTaushanov.

**Comment by nnaydenow** [comment]
Test looks good to me but I haven’t review the rest of  PR.

**Review by tsanislavgatev — APPROVED** [review]

**Comment by tsanislavgatev** [comment]
Merge main into your branch to get the change that makes the tests stable.

**Comment by nnaydenow** [comment]
Test is failing because following code doesn't work and the focus is not restored to the button when the menu is closed.
```
	<ui5-button id="test">Open Menu</ui5-button>
	<ui5-menu>
		<ui5-menu-item text="New File">
		</ui5-menu-item>
	</ui5-menu>
	<script>
			const button = document.querySelector("#test")

			button.addEventListener("click", (e) => {
				const menu = document.querySelector("[ui5-menu]")
				menu.open = true;
				menu.opener = e.target;
			})
	</script>
```

**Review by nnaydenow — APPROVED** [review]

**Review by tsanislavgatev — APPROVED** [review]
After discussion and additional test we've came to the conclusion that the latest version works as expected and described in the issue.

**Pull request merged**
