### PR TITLE
feat(ui5-button): introducing attention type button

### PR DESCRIPTION
**Pull request by tsanislavgatev**
fixes: https://github.com/SAP/ui5-webcomponents/issues/3446

### CODE REVIEW

**Comment by ilhan007** [comment]
Hi @tsanislavgatev I saw that "Attention" type is added, the issue mentions also the "Critical" type, is there a reason not to add it or it's planned for different change later on

**Comment by tsanislavgatev** [comment]
Hi @ilhan007,
I am not aware of Critical type implementation planned.
But as far as i can see is Critical / Attention which I understand as one of them. And in the explanation given by Marcus it's stated that they need a Warning type of button in brackets asked for one of them both.

**Review by ilhan007 — APPROVED** [review]

**Comment by ilhan007** [comment]
Looks good to me @SAP/ui5-webcomponents-topic-b  to still review

**Comment by MarcusNotheis** [comment]
> Hi @ilhan007,
> I am not aware of Critical type implementation planned.
> But as far as i can see is Critical / Attention which I understand as one of them. And in the explanation given by Marcus it's stated that they need a Warning type of button in brackets asked for one of them both.

Yes, the Attention Design is totally sufficient for me :) I was just not sure which name you would prefer in your implementation so I listed both options that are used in UI5 🙂

**Review by NHristov-sap — APPROVED** [review]

**Pull request merged**
