### PR TITLE
fix(ui5-combobox): User action cancelled when clicking "X" on mobile

### PR DESCRIPTION
**Pull request by Martotko**
Fixes: #2449

### CODE REVIEW

**Review by MapTo0 — CHANGES_REQUESTED** [review]
_selectedItem sounds a little bit strange. Maybe _selectedItemText / TItle ??

+ add tests

**Comment by Martotko** [comment]
> _selectedItem sounds a little bit strange. Maybe _selectedItemText / TItle ??
> 
> * add tests

Variable is updated. About the test, I wasn't able to simulate a mobile device so as to test it, furthermore, there don't have any tests for mobile devices.

**Review by MapTo0 — APPROVED** [review]

**Review by ilhan007 — CHANGES_REQUESTED** [review]
thanks for the fix, just hold for a while until I check it please

**Review by ilhan007 — CHANGES_REQUESTED** [review]
Does not seem to work as expected

Here you can see openui5 cbx with selected "Bulgaria", open the picker, you can see "Bulgaria", clicking "X" - you see Bulgaria

https://user-images.githubusercontent.com/15702139/107621233-9952d400-6c5e-11eb-96cb-ceb94478227a.mov


The Current change: "Bulgaria' is selected, open the picker - "Bulgaria" is already lost, close the picker with X, "Bulgaria" is lost:

https://user-images.githubusercontent.com/15702139/107621425-e9ca3180-6c5e-11eb-9f95-335539493d76.mov

**Review by ilhan007 — APPROVED** [review]

**Pull request merged**
