### PR TITLE
fix(ui5-busyindicator): add a11y support

### LINKED ISSUE #2381: ui5-busyindicator accessibility issues
**Describe the bug**
The ui5-busyindicator is not being read by screenreaders and has no tooltip.

**To reproduce**
1. Using any screenreader (NVDA, JAWS, VoiceOver)
2. go to https://sap.github.io/ui5-webcomponents/playground/components/BusyIndicator/
3. click the 'Fetch List Data' button
4. notice the busy indicator is shown, but nothing read out by the screenreader
5. hover the mouse over any of the 3 busy indicators (Small, Medium, Large) at the top of the page
5. notice there is no tooltip

**Expected behavior**
1. When the busy indicator is shown, the screenreader should read out "Please wait"
2. When hovered, the 3 dots should have a tooltip reading "Please wait"

**Affected components**
ui5-busyindicator

**Organization:**
SuccessFactors

**Priority:**
Medium

Thank you

### PR DESCRIPTION
**Pull request by dimovpetar**
- Tooltip is now shown on hover
- Focus is now on the correct div, so screen readers can read it properly

Fixes #2381 

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [x] [Correct commit message style](https://github.com/SAP/ui5-webcomponents/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Review by TeodorTaushanov — APPROVED** [review]

**Review by GerganaKremenska — APPROVED** [review]

**Review by ilhan007 — CHANGES_REQUESTED** [review]
Hi @dimovpetar could you check if the following is caused by this change, as I can't reproduce it in the master. The loading text looks shifted downwards with this change

Screenshot 2021-03-30 at 17 39 28

Previously it was right below the dots
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/BusyIndicator/

**Comment by dimovpetar** [comment]
> Hi @dimovpetar could you check if the following is caused by this change, as I can't reproduce it in the master. The loading text looks shifted downwards with this change
> 
> Screenshot 2021-03-30 at 17 39 28
> 
> Previously it was right below the dots
> https://sap.github.io/ui5-webcomponents/master/playground/main/pages/BusyIndicator/

Yes, I have fixed it now. Also added the case in BusyIndicator.html

**Review by ilhan007 — APPROVED** [review]

**Comment by ilhan007** [comment]
Hello @ SAP/ui5-webcomponents-topic-rd please update the BusyIndicator Accessibility wiki page.

**Comment by dimovpetar** [comment]
> Hello @ SAP/ui5-webcomponents-topic-rd please update the BusyIndicator Accessibility wiki page.

Wiki is now updated :)

**Comment by ilhan007** [comment]
Thanks @dimovpetar !

**Pull request merged**
