### PR TITLE
fix(ui5-dialog): correctly restore body scrolling on ESC

### LINKED ISSUE #3690: ui5-dialog: scrolling is blocked when dialog is closed with `Esc` key
### **Bug Description**
If a `ui5-dialog` is closed with the `Escape` key, it seems like it doesn't remove the scroll blocking. If you close if the the `close()` method, the scroll blocking gets removed as expected.

### **Expected Behavior**
Scroll Blocking should be removed when closing the dialog via `Esc`, like in `1.0.0-rc.14`.

### **Steps to Reproduce**
1. Open: https://codesandbox.io/s/thirsty-bouman-cb80u?file=/src/App.js
2. Scroll through the page, everything is working fine.
3. Click `Open Dialog`, close it with the `close` button in the footer, try to scroll again. --> Still works fine
4. Click `Open Dialog` again, then press `Esc` and try to scroll again. --> Scrolling is now blocked
5. _Optional: open the dialog again and press the close button, scrolling works fine again_

### **Isolated Example**
https://codesandbox.io/s/thirsty-bouman-cb80u?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: macOS
- Browser: Chrome 92.0.4515.131
- Affected component: `ui5-dialog`, maybe even the base class `ui5-popup`?

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Customer Advisory / UI5 Web Components for React

### PR DESCRIPTION
**Pull request by dimovpetar**
Body scrolling is now blocked only on first call of `blockBodyScrolling` and restored on the last call of `unblockBodyScrolling`. 

Fixes #3690

### CODE REVIEW

**Review by ilhan007 — APPROVED** [review]

**Review by alexandar-mitsev — CHANGES_REQUESTED** [review]
also fix OpenedPopupsRegistry.js, line 38 should be
openedRegistry[openedRegistry.length - 1].instance.close(true);
instead of
openedRegistry.pop().instance.close(true);

this on its own is also fixing the issue, but can be fixed in combination

**Comment by dimovpetar** [comment]
> also fix OpenedPopupsRegistry.js, line 38 should be
> openedRegistry[openedRegistry.length - 1].instance.close(true);
> instead of
> openedRegistry.pop().instance.close(true);
> 
> this on its own is also fixing the issue, but can be fixed in combination

You are right, I've changed the OpenedPopupsRegistry to not implicitly remove the popup.
But the logic in Popup.js is still needed, because there might be a popup that is not blocking the scrolling. Therefore, we need to maintain information about those blockers.

**Review by alexandar-mitsev — APPROVED** [review]

**Review by ilhan007 — APPROVED** [review]

**Comment by Lukas742** [comment]
Hi colleagues,

could you kindly also include this in the next release of the `0.31` sf branch. Thanks :)

**Comment by ilhan007** [comment]
Hi @Lukas742 yes, we will do that

**Pull request merged**
