### PR TITLE
fix(ui5-ComboBox):  avoid flickering problem

### LINKED ISSUE #2365: Combobox flickers continuous when you open the drop-down
**Describe the bug**

Combobox flickers when you open the drop-down 

**To reproduce**
1. use Combobox :
<ui5-combobox placeholder="Enter value">
	<ui5-cb-item text="Item 1"></ui5-cb-item>
	<ui5-cb-item text="Item 2"></ui5-cb-item>
	<ui5-cb-item text="Item 3"></ui5-cb-item>
</ui5-combobox>

**Expected behavior**
the drop-down can be open by clicking arrow or by pressing f4. 
but not. the drop-down list flickers continuous.

**Context**
- UI5 Web Components version "1.0.0-rc.9",
- OS/Platform: {macos} 
- Browser *(if relevant)*: {chrome} 
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(furo.pro)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

### PR DESCRIPTION
**Pull request by f-zou**
fix(ui5-ComboBox):  avoid flickering problem

use the right activeElement by focus-checking to solve the flickering problem of the comboBox.

Fixes #2365

### CODE REVIEW

**Comment by ilhan007** [comment]
Hello @f-zou

thanks for your contribution, the build fails because of  eslint errors:

```sh

/home/travis/build/SAP/ui5-webcomponents/packages/main/src/ComboBox.js
  424:1   error  Expected indentation of 3 tabs but found 12 spaces  indent
  424:65  error  Strings must use doublequote                        quotes
  425:1   error  Expected indentation of 2 tabs but found 8 spaces   indent
```

**Review by ilhan007 — CHANGES_REQUESTED** [review]
Thanks for the fix. In order to merge it you need to provide a test?
Perhaps you can simulate click in the input and check for the focused property.
The ComboBox test are in packages/main/test/specs/ComboBox.spec.js

To run the test (set up the project first-  yarn, then yarn build (just the very first time), yarn start to have the server running)

```js 
cd packages/main
yarn run wdio ../tools/components-package/wdio.js --spec test/specs/ComboBox
```

**Comment by f-zou** [comment]
> Thanks for the fix. In order to merge it you need to provide a test?
> Perhaps you can simulate click in the input and check for the focused property.
> The ComboBox test are in packages/main/test/specs/ComboBox.spec.js
> 
> To run the test (set up the project first- yarn, then yarn build (just the very first time), yarn start to have the server running)
> 
> ```js
> cd packages/main
> yarn run wdio ../tools/components-package/wdio.js --spec test/specs/ComboBox
> ```

Hallo @ilhan007 
thanks for you reply. i have added the tests  8 days ago. could you pleas check the commits when you have time. 

thank you.

Best
fan

**Comment by ilhan007** [comment]
> > Thanks for the fix. In order to merge it you need to provide a test?
> > Perhaps you can simulate click in the input and check for the focused property.
> > The ComboBox test are in packages/main/test/specs/ComboBox.spec.js
> > To run the test (set up the project first- yarn, then yarn build (just the very first time), yarn start to have the server running)
> > ```js
> > cd packages/main
> > yarn run wdio ../tools/components-package/wdio.js --spec test/specs/ComboBox
> > ```
> 
> Hallo @ilhan007
> thanks for you reply. i have added the tests 8 days ago. could you pleas check the commits when you have time.
> 
> thank you.
> 
> Best
> fan

There was no test at the time I asked for test. Anyway, thanks for adding it. I will approve the PR.
Thanks a lot for contributing this fix.

**Review by ilhan007 — APPROVED** [review]

**Comment by f-zou** [comment]
@ilhan007 

thank you very much. will this fix automatically be merged in to master or do i need to do something from my side?

**Comment by ilhan007** [comment]
The fix will be released as part of the rc.10 release at the end of the next week

**Pull request merged**
