### PR TITLE
feat(playground): next playground with storybook

### PR DESCRIPTION
**Pull request by dobrinyonkov**
Introducing StorybookJS as replacement of the current Jekyll playground.

**How to use:** 

`yarn build` inside root - to generate custom-elements.json

`yarn storybook` inside the `packages/playground` - to serve for local development

**Summary:**
- With this change we will have  both playgrounds (Jekyll and Storybook) in parallel (Storybook will be served on /_playground)
- Stories are written in CSF format (https://storybook.js.org/docs/web-components/api/csf) and are located in the packages/playground/_stories folder.
- After this change is merged, we will start migrating the the `*.sample.html` files to Storybook stories. (Avatar, AvatarGroup, Select, List are migrated and included with this PR) 
- The migration will be done in a separate PR and new files will be auto generated by a script that transforms the current `*.sample.html` snippet sections to an entry level CSF stories. 
Component owners will further improve the stories and add more stories for the components.
- Users will now be able to test the APIs live in the playground and see the markdown code of the story in the docs tab.
- For every component there is a folder inside the `_stories` folder. A file named `argsTypes` is generated automatically which holds overrides of some of the properties that are displayed inside the args tables of the storybook playground
- enums are overidden because storybook does not handle enums well 
-  slots are overidden in the typescript interface because ts complains about the types of the slots being strings 

#6032 - Stories generated from all `*.sample.html` files.

Additional files are generated and not pushed to the repo but only created at built time when the following scripts are executed:
`documentation-prepare.js` - copies the `docs/*.md` files to `packages/playground/docs/*.mdx` and define them as documentation files for the storybook playground. (Add Meta tag, etc.)
`parse-manifest.js` - imports both `[fiori, main]/custom-elements.json` files, creates one and removes the attributes to avoid double render of the properties.
`samples-prepare.js` - goes through all directories inside the `_stories` folder and creates  a file called `argTypes.js`  later imported by every story to describe the enums an their options.

 **Storybook folders and files explained:**
- `.storybook` - holds all configuration files.
-  - `main.js` - The main configuration file. This file controls the Storybook server's behavior, so you must restart Storybook’s process when you change it.
- - `preview.js` - this file controls the way stories are rendered and can also add global [decorators](https://storybook.js.org/docs/web-components/writing-stories/decorators#global-decorators) and [parameters](https://storybook.js.org/docs/web-components/writing-stories/parameters#global-parameters),
- - `manager.js` - To control the behavior of Storybook’s UI. Use to set [UI options](https://storybook.js.org/docs/web-components/configure/features-and-behavior) and to configure Storybook’s [theme](https://storybook.js.org/docs/web-components/configure/theming)
- - `preview-head.html` - use this file to add extra elements to the head of the preview iframe that components are laoded for the live playground (add `preview-body.html` to add elements to the body) 
- `build-storybook-scripts` - hold scripts run at build time to prerare resources for stories 

Co-authored-by: PetyaMarkovaBogdanova <petya.markova-bogdanova@sap.com>
Co-authored-by: PlamenIvanov <plamen.ivanov01@sap.com>

### CODE REVIEW

**Comment by nnaydenow** [comment]
Some initial thoughts: 
- Is it possible to add static page which will be used outside StoryBook (for example landing page)?
- We have to discuss how to filter or how to mark properties like isUi5Element because they are not public ones.
- Can we remove configuration toolbar for pages without samples?

There are a lot of errors inside the consoles about HTML structure and used CSS - maybe we need to refactor them somehow.

**Comment by ilhan007** [comment]
@dobrinyonkov after you address the questions from Nayden, you can go ahead and merge it. 
Then, the playgrounds (old and new) will co-exist. After merging the PR, you will probably need to show the other teams how to create their samples, if there is no generation step. And after we have most of the samples in place, we can replace the old playground with the new one.

Ideally, we would like to keep the landing page. Currently, it seems it depends on jekyll to generate source paths correctly.
So, this would be next task of the story - to make landing page work without jekyll, so that we can remove jekyll entirely. 
At the end, we imagine pressing the "getting started" button of the landing page to open the Story Book based Playground.

**Comment by ilhan007** [comment]
Here are my findings testing the [preview](https://dobrinyonkov.github.io/ui5-webcomponents/_playground/?path=/story/components-bar--template-0)
- the **default theme** should be **Morning Horizon**
- on initial load the **theme is not selected** in the Theme drop down
- the components miss the **since** and **package** information, right next to their name (as it's currently in our docs)
- d**ynamic API changes** via the UI seems not working at the moment
- the **order of the components** can be improved, either the as it's now, or **"main" components should be first** in the menu
- it's good to show the **latest version** and **github icon** in the storybook bar at the top-right

**Comment by dobrinyonkov** [comment]
Resolved comments from https://github.com/SAP/ui5-webcomponents/pull/5831#issuecomment-1422903787

[Demo](https://dobrinyonkov.github.io/ui5-webcomponents/_playground)

- Updated the stortybook to version 7.0
- - vite support is first level and uses the vite.config.js directly. Removed `@storybook/builder-vite` package.
- - there are some visual updates with the new version. Docs page is now displayed as a node in the tree of stories and not in the toolbar.  
image


- Ordered of components improved  -> `main` -> `fiori`
- Default theme is Morning Horizon and selected by default.
- Since and package information added
- Github button added in the storybook toolbar - currently seems not to be possible to align it to the right of the toolbar
image

Latest version information is still displayed on the landing page as with the previous playground.
Do we add it to the storybook as well? 
Maybe as an addon (link/button) in the toolbar next to the Github button)

**Comment by ilhan007** [comment]
Some visual points to discuss:

- The since, package, tag info don't look nicely placed with the Overview title, we can discuss how to arrange them.
Screenshot 2023-02-14 at 13 02 55

- Some space between the ES6 import and the sample would be better
Screenshot 2023-02-14 at 13 02 47

- Good to have a logo. It looks a bit misaligned (vertically) when looking the actions (theme, dir) in the main pane.
It will look better if they are aligned
Screenshot 2023-02-14 at 13 06 12

- Good to have the GitHub btn, somehow I imagined to be on the right side, next to the latest version text (missing here)
and the full-screen button moved to the left side next to other actions  (theme, dir):
Screenshot 2023-02-14 at 13 17 50



- Minor, but it's easy to address would be nice to align the the tags
Screenshot 2023-02-14 at 13 03 41

Screenshot 2023-02-14 at 13 14 23

**Review by ilhan007 — APPROVED** [review]
Overall looks good, I published comments, but they could be be addressed later

**Comment by dobrinyonkov** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/issues/4336

**Pull request merged**
