### PR TITLE
feat(ui5-menu): make the item click event cancellable

### PR DESCRIPTION
**Pull request by unazko**
Requirement:
- Currently the menu closes when a menu item gets selected.
- Enable users to press multiple menu items.

Fixes: #5600

### CODE REVIEW

**Comment by unazko** [comment]
I've put this pull request for an implementation review.
In the meantime I'll update the PR with a sample and a test.

**Review by didip1000 — CHANGES_REQUESTED** [review]
The change works but i think the note needs to be reworded to something like:
Since 1.14.6 the event is preventable, allowing the menu to remain open after an item is selected.

**Comment by unazko** [comment]
> The change works but i think the note needs to be reworded to something like: Since 1.14.6 the event is preventable, allowing the menu to remain open after an item is selected.

done

**Review by didip1000 — APPROVED** [review]

**Review by nnaydenow — CHANGES_REQUESTED** [review]
Temporary blocking the merge due the release

**Comment by ilhan007** [comment]
Hello @unazko "Enable users to select multiple menu items without the need to re-open the menu after each selection.
" how this is handled as I can't see selected property selection modes been supported by Menu Items

**Comment by unazko** [comment]
> Hello @unazko "Enable users to select multiple menu items without the need to re-open the menu after each selection. " how this is handled as I can't see selected property selection modes been supported by Menu Items

Hi @ilhan007, by selection I've meant triggering a press over an item. Application developers would decide in the attached handler what action will be performed. Your remark is correct as the selection in the menu is specified as hover and focus (basic menu navigation). The use case from the requirement is to trigger press over a couple of menu items, which will trigger different statistical data to be displayed in a diagram next to the menu. The visualization would be modified by application via setting an icon over the pressed menu items for indication.

**Review by ilhan007 — APPROVED** [review]

**Comment by vladitasev** [comment]
@unazko A strange file was submitted with this change, probably by mistake. Please look into it

**Pull request merged**
