### PR TITLE
fix(ui5-input): allow entering numbers with dot as a separator

### LINKED ISSUE #5983: Writing numbers with a "dot" as decimal point using input type="Number" clears the input
### **Bug Description**
While entering a decimal number using a "dot" as a separator the input field gets empty in chrome and in safari it triggers a 
`InvalidStateError` `The input element's type ('number') does not support selection.` 

This makes the Input element useless for countries which uses the "dot" as separator.

### **Expected Behavior**
Allow entering numbers with dot as a decimal point, like in 1.7.1 and before

### **Steps to Reproduce**
1. Set your browser to a locale which uses "dot" as decimal point like Switzerland, or one of [this list](https://en.wikipedia.org/wiki/Decimal_separator#:~:text=Switzerland%3A%20There%20are%20two%20cases,%2C%22%20as%20the%20decimal%20separator.)
2. Enter a digit followed by a "dot"

### **Isolated Example**
 [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-biwthg?file=/src/index.js)

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: MacOs
- Browser: Chrome, Safari
- Affected component: Input
 
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Note:** As a user you can use a comma to enter a number, but this feels "strange"

### PR DESCRIPTION
**Pull request by veith**
The input value is not cleared anymore during typing.

Fixes #5983

### CODE REVIEW

**Comment by veith** [comment]
If you want to enter the number 1.5, the value of the ui5-input element still changes from 1 to "" to 1.5 during typing and fires input events with meaningless intermediate values. I can fix this too, if you want.

**Comment by ndeshev** [comment]
Hello @veith 

Your pull-request is named "allow entering numbers with dot as a separator"
Its message is The input value is not cleared anymore during typing.
and the commit message  - do not emit meaningless events

All of these sounds like different issues :)  the changed code is related to the commit message
I can't reproduce a case where the value gets cleared, I don't know if it is because of the locale.

We do not want to prevent firing of the event in the case of the added condition as now it behaves like the native input - it will fire event even if the backspace is pressed while the value is NaN (e.g. - 1.)

I tested on WinOS on Chrome.

Kind regards,
Nikolay

**Comment by veith** [comment]
hi @ndeshev 
I agree, and will revert the second commit.

**Comment by veith** [comment]
@ndeshev Can i do something to trigger the checks again?

**Comment by ilhan007** [comment]
> @ndeshev Can i do something to trigger the checks again?

Hi @veith the checks have been restarted

**Pull request closed without merging**
