### PR TITLE
chore: release 1.0.0-rc.15

### PR DESCRIPTION
**Pull request by ilhan007**

### CODE REVIEW

**Review by vladitasev — APPROVED** [review]

**Review by fifoosid — DISMISSED** [review]

**Review by fifoosid — COMMENTED** [review]
There is a merge conflict

**Review by vladitasev — APPROVED** [review]

**Comment by MarcusNotheis** [comment]
Quickly chatted with Ilhan yesterday: the `ui5-notification-list-item` and `ui5-notification-list-group-item` are still using `heading` instead of `title-text`. Is this intended?

**Review by fifoosid — COMMENTED** [review]
Shouldn't you change the hash of the theme-base package since you are changing a file from that package?

**Review by fifoosid — APPROVED** [review]

**Comment by fifoosid** [comment]
> Quickly chatted with Ilhan yesterday: the `ui5-notification-list-item` and `ui5-notification-list-group-item` are still using `heading` instead of `title-text`. Is this intended?

This is addressed [here](https://github.com/SAP/ui5-webcomponents/pull/3586)

**Review by fifoosid — DISMISSED** [review]

**Review by fifoosid — APPROVED** [review]

**Pull request merged**
