### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I309691 @I352919 @I301342

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I309691 @I352919 @I301342

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I309691 @I352919 @I301342

**Comment by vladitasev** [comment]
We must merge: https://github.com/SAP/ui5-webcomponents/pull/1826 and then we can retrigger the job in the translation system, so that it can make another PR from the new master, and the build may pass.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I309691 @I352919 @I301342

**Pull request merged**
