### PR TITLE
chore: add missing quotation marks in build scripts

### PR DESCRIPTION
**Pull request by xpr0gamers**

### CODE REVIEW

**Comment by fifoosid** [comment]
Hi @xpr0gamers 

In order to continue with merging this PR, you should sign the license/cla of the repo

**Review by fifoosid — CHANGES_REQUESTED** [review]
The changes in this pull request should be separated in two different PRs, because they are regarding two different topics.

**Comment by xpr0gamers** [comment]
@fifoosid Sorry, my mistake. Now it should be clean.

**Review by vladitasev — APPROVED** [review]

**Review by fifoosid — APPROVED** [review]

**Comment by fifoosid** [comment]
> @fifoosid Sorry, my mistake. Now it should be clean.

Thanks for the contribution

**Pull request merged**
