### PR TITLE
feat(ui5-carousel): Implement F7 keyboard functionality

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
Part of #3092

### CODE REVIEW

**Review by gmkv — CHANGES_REQUESTED** [review]
On http://localhost:8080/test-resources/pages/Carousel.html
If the focus is on a list item within a card, pressing F7 twice will not restore the focus to the same item.
_onfocusin in the Carousel does not get called every time - in particular, when the focus moves from the card header to the list in the card.

Can you also write a test?

**Comment by TeodorTaushanov** [comment]
> On http://localhost:8080/test-resources/pages/Carousel.html
> If the focus is on a list item within a card, pressing F7 twice will not restore the focus to the same item.
> _onfocusin in the Carousel does not get called every time - in particular, when the focus moves from the card header to the list in the card.
> 
> Can you also write a test?

Tests are added.

The ui5-list stops propagation of the "focusin" event. For that F7 keyboard navigation doesn't work for it. This should be fixed in the ui5-list.

**Review by gmkv — APPROVED** [review]

**Review by ilhan007 — APPROVED** [review]

**Review by ilhan007 — APPROVED** [review]

**Comment by ilhan007** [comment]
+1, someone from @SAP/ui5-webcomponents-topic-rd should also review the change

**Review by dimovpetar — APPROVED** [review]

**Comment by ilhan007** [comment]
If this was the last change related to the Keyboard Handling epic, you can close the issue
https://github.com/SAP/ui5-webcomponents/issues/3092

**Pull request merged**
