### PR TITLE
fix(ui5): change "focus-visible" pseudo selector to "focus"

### LINKED ISSUE #6895: [SAP][RadioButton]: Focus is not present on initial selection of radio button.
### Describe the bug

When a user selects a radio button or a radio button is selected by default, it does not have an outline to represent that the button is focused. 

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--docs

### Reproduction steps

1. Click on radio button
2. use arrow keys to navigate among radio buttons 
3. Outline is present to highlight the focused button

### Expected Behaviour

Outline around the button should be present for initial as well as default selection.

### Screenshots or Videos

https://user-images.githubusercontent.com/129057796/231126634-f0bc6332-8654-4ec9-a291-b85f8c4d7ec6.mp4

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Additional Context

_No response_

### Relevant log output

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### LINKED ISSUE #7098: Carousel - Focus missing
### Bug Description

The focus of the Carousel doesn’t appear when you click on it

### Affected Component

ui5-carousel

### Expected Behaviour

image

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Carousel/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Organization

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
This change reverts #6084

Fixes #7098
Fixes #6895

### CODE REVIEW

**Review by ilhan007 — APPROVED** [review]

**Comment by ilhan007** [comment]
Hi @boghyon according to the Accessibility experts the accessibility quality is affected and we decided to revert it back for now.

**Comment by boghyon** [comment]
@ilhan007 It'd be interesting to know on which accessibility standard exactly the argument against `focus-visible` bases.

**Comment by pskelin** [comment]
@boghyon the keyboard spec states that for desktop users, the focus must always be visible so they can quickly continue working after a call or a distraction without thinking where the focus is. It also refers to an ISO standard: ISO 9241-171 9.2.2.

We cannot argue when a standard mandates this behaviour.

`focus-visible` will still be used for mobile users, which is not reflected by this change. For mobile, the focus should be visible only if a physical keyboard interaction occurs. We are still discussing the details.

**Comment by boghyon** [comment]
Hi @pskelin,

Based on this sample https://jsbin.com/roputeb/edit?html,css,output, we can see that the web standard `focus-visible`, which is explicitly designed to help web authors to avoid violating focus visibility,\* meets the mentioned ISO standard **for keyboard-centric users**.
- The **focus indicator is always visible** even from a few meters distance **without further interaction.**
- Even for pointer-centric users (e.g. mouse), the user agent (browser) draws the focus indicator on `<input>` or `<select>` elements.


Moreover:
- [Technique C40 from WCAG](https://www.w3.org/WAI/WCAG22/Techniques/css/C40) explicitly mentions that **`focus-visible` can be used as a sufficient technique to meet the [2.4.7: Focus Visible](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible) success criterion.**

<br>

___

\* One of the reasons why I'm in strong favor of `focus-visible`: having the focus ring **always visible encourages inexperienced (UI5) devs to remove the indicator completely.**

 * [How do I remove focus dotted line in UI5 input field?](https://stackoverflow.com/q/67840488/5846045)
 * https://answers.sap.com/questions/452694/css-outline-issue-while-focus.html
 * https://answers.sap.com/questions/144885/ui5-icontabbar-icontab-shows-dotted-square-when-yo.html?childToView=145003
 * https://answers.sap.com/questions/11574379/changing-sapui5-style-with-css-when-getting-focus.html?childToView=11864292
 * From an empirical standpoint, I can sadly say that even professional "Fiori consultants" were and are guilty of this "quick fix", but defend their decision by saying that the always visible focus indicator in desktop is not desirable for their customers who are mouse-centric users.

**Pull request merged**
