### PR TITLE
fix(ui5-input): add parts to support css customization

### PR DESCRIPTION
**Pull request by slin-sap**
### PR checklist
- [x] Check the [Development Hints](https://sap.github.io/ui5-webcomponents/docs/contributing/DoD/)

- [x] Follow the [Commit message Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#commit-message-style)

For example: `fix(ui5-*): correct/fix sth` or `feat(ui5-*): add/introduce sth`. If you don't want the change to be part of the release changelog - use `chore`, `refactor` or `docs`.

- [x] Add proper description about the background of the change and the change itself

Added 3 `part` attributes to elements in ui5-input shadow dom, in order to support css customization on ui5-input. Namely:

`part: "root"` E.g. When border-radius is changed, this makes sure focused style can be adjusted as well with same border radius.
`part: "input"` E.g. customize color of placeholder text, 
`part: "clear-icon" ` E.g. customize color of built-in close icon.

- [ ] Link to an existing issue (if available)

Use `Fixes: {#PR_NUMBER}` to close the issue automatically when the PR is merged
or `Related to: {#PR_NUMBER}` to just create a link between the PR and the issue.

- [x] Read the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by slin-sap** [comment]
@ilhan007 

Thanks for helping us earlier in #8917. We have another scenario that need applying customized css styling on ui5-input. I have tested that adding these part attribute allowed the customized css to be applied successfully. Could you or your colleague review this PR and let me know if this PR needs any improvement to be accepted?

**Comment by ilhan007** [comment]
Hi @SAP/ui5-webcomponents-topic-rl can you review this PR, it adds two shadow parts to make things more customisable from outside. If you have further questions, you can also follow up internally with the author.

**Comment by slin-sap** [comment]
The default css class for focus is "ui5-input-focusable-element". This css class is added to the root div.

Our UI design requires a rounded border on ui5-input. When ui5-input is clicked, the default focused blue border is shown over our rounded border, but these two border do not perfectly overlay, and user could see both. Therefore, customizing the root <div> is required in our case.

I have seen other ui5 webcomponents using part="root". E.g. https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/Card.hbs#L5

**Comment by ilhan007** [comment]
Colleagues @ivoplashkov @elenastoyanovaa @hristop @MapTo0 the PR looks fine to me, root is something that we will always have, native input as well, and the clear icon also seems integral part. So I think we can merge this PR, from my side +1

**Review by ilhan007 — APPROVED** [review]

**Comment by ilhan007** [comment]
@slin-sap can you update the PR with the main branch - the failing build was fixed in the meantime.

**Review by ilhan007 — COMMENTED** [review]
you have to list them in the component's overview with `@csspart`

**Comment by slin-sap** [comment]
> Hi @slin-sap
> 
> you have to list them in the component's overview with `@csspart` in the `Input.ts`:
> 
> ```ts
>  /**
>  * ...
>  * @csspart root - some description
>  * @csspart input - some description
>  * @csspart clear-icon - some description
>  * @constructor
>  * @extends UI5Element
>  * @public
>  */
> @customElement({
> 	tag: "ui5-input",
> ```

@ilhan007  Please check the updated file with csspart decorators added.

**Review by hristop — APPROVED** [review]
@slin-sap  The PR is approved, you can merge it :)

**Comment by ilhan007** [comment]
@slin-sap this has been released with 2.2.0

**Pull request merged**
