### PR TITLE
feat(ui5-list): preventable item-click event

### PR DESCRIPTION
**Pull request by plamenivanov91**
In this change we introduce the preventable behaviour of the item-click
event in the List component.

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [x] [Correct commit message style](https://github.com/SAP/ui5-webcomponents/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Comment by nnaydenow** [comment]
#1618

**Comment by nnaydenow** [comment]
Looks good to me. Currently ui5-item-press is used only internally and it shouldn't be part of the prevention.

**Review by nnaydenow — APPROVED** [review]

**Comment by ilhan007** [comment]
Could you also add Fixes: link of the issue in the commit message. It can be edited in the Github UI, but later when you press the Squash and merge button, you need to fix it and make sure `Fixes: link of the issue` is added.

**Comment by plamenivanov91** [comment]
Hi @ilhan007 ,

Sorry but I saw your comment after I merged it. It seems like the issue has closed automatically since it's linked with the pull request.

**Pull request merged**
