### PR TITLE
fix(ui5-multi-combobox): select all implementation

### PR DESCRIPTION
**Pull request by MapTo0**
FIXES: #5537

### CODE REVIEW

**Review by niyap — CHANGES_REQUESTED** [review]
1. I want to discuss with the team the following scenario:
- open the N-more popover
- deselec from SelectAll button 
-> what is the expected result, to have the filtered items but not selected.. if so, isn't it meaningful when the focus is moved to the input field to have the list with the suggestions?
2.  On mobile device - open the picker, select some suggestions, press show selected button, then deselect all the suggestins (the list remains filtered and the show selected button pressed), press it again in order to see the whole list but do not select any suggestion, then press it once again -> there is no selected suggestions but the "Select All" is presented and selected with the label 0 of 27 which is strange

**Comment by niyap** [comment]
Scroll the suggestions making the first one not visible, close the picker, open it again. Navigate via arrow down through the suggestions - when the focus is over the first one, the list is not scrolled and the item is not visible when on focus

**Review by niyap — APPROVED** [review]

**Comment by niyap** [comment]
Please, create feature request to ui5-list owners before completing the task.

**Comment by MapTo0** [comment]
Feature request for clean implementation: https://github.com/SAP/ui5-webcomponents/issues/8165

**Pull request merged**
