### PR TITLE
refactor(ui5-li): selected property changed to private

### PR DESCRIPTION
**Pull request by yanaminkova**
The `selected` property of the `ui5-li` has been redefined within the class where it is actively utilized. Despite this change, it remains accessible to all components that rely on it.

Related to https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

### CODE REVIEW

**Review by nnaydenow — DISMISSED** [review]
add `declare` keyword in front of the places where we only want to change the documentation

**Comment by nnaydenow** [comment]
FYI @MapTo0

**Comment by dobrinyonkov** [comment]
Related to https://github.com/SAP/ui5-webcomponents/issues/9022

**Comment by yanaminkova** [comment]
> add `declare` keyword in front of the places where we only want to change the documentation

We only need to update the documentation for the `ui5-li-notification` and `ui5-li-notification-group` components to remove the `selected` property. The documentation for all other components should remain unchanged. 
Is the `declare` statement still required in this scenario?

**Comment by tsanislavgatev** [comment]
@dobrinyonkov @yanaminkova
We've merged: https://github.com/SAP/ui5-webcomponents/pull/8871
We inherit ListItemBase and document the selected property as unusable in our case.
Can you please delete our documentation of the selected property in the MenuSeparator component, as the only reason to document it is because of the inheritance?

**Review by kineticjs — APPROVED** [review]
So my understanding is that we define the "select" property in the base class only (i.e in ListItemBase) and then declare it as inherited property in the subclasses where it makes sense to use it.. In the remaining places (MenuSeparator) no mentioning (i.e. no declaration/definition) of the "select" property. Seems coherent, so approving...

**Review by ilhan007 — APPROVED** [review]

**Pull request merged**
