### PR TITLE
fix(ui5-textarea): onPaste event fixed for Firefox

### PR DESCRIPTION
**Pull request by Martotko**
Fixes: #2719

### CODE REVIEW

**Comment by Martotko** [comment]
Hi,

The webdriverio keys "Meta" and "Control" don't work properly and because of that the fix can't be tested.

Best regards,
Martin

**Comment by Martotko** [comment]
The problem is reported to the Firefox browser support - https://bugzilla.mozilla.org/show_bug.cgi?id=1689317

**Review by MapTo0 — CHANGES_REQUESTED** [review]
this will fire double past event on chrome, right? can we make that change for FF only and comment with a link to the bugzila

**Comment by ilhan007** [comment]
Closing the PR as the issue will be fixed with FF version 87 - 2021-03-22.

**Pull request closed without merging**
