### PR TITLE
fix(ui5-datetime-picker/ui5-time-picker): fix top and bottom overflows of input

### PR DESCRIPTION
**Pull request by hinzzx**
There was a little overflowing in the input fields of the `ui5-datetime-picker` and the `ui5-time-picker` as we can see from the example below.

### Before:
image

There should be margin, but it should not be visible as it was:

### After:
image
image

Fixes: #5912 
Fixes: #7021 
Fixes: #7104

### CODE REVIEW

**Review by tsanislavgatev — CHANGES_REQUESTED** [review]
remove changes in timelineitem css. The rest of the change looks fine to me.

**Review by ilhan007 — DISMISSED** [review]
The margins `--_ui5_input_margin_top_bottom: 0.25rem;` of the Input have been added by this change: https://github.com/SAP/ui5-webcomponents/pull/6044 to full-fill the visual design specs, did you check if the same margins are needed for (Date)TimePicker components as they are input components as well.
 Because, I assume that in terms of the styling of the input field itself (inlc. paddings/margins), the DateTimePicker, TimePicker should have the same visual as the Input. 
Because all these components are form components and potentially will be use together and differences in the layout will cause alignment issues.

If these margins are required (after checking the visual specs) you need to move them from the inner ui5-input to the ui5-(date)time-picker host.

**Comment by hinzzx** [comment]
> The margins `--_ui5_input_margin_top_bottom: 0.25rem;` of the Input have been added by this change: #6044 to full-fill the visual design specs, did you check if the same margins are needed for (Date)TimePicker components as they are input components as well. Because, I assume that in terms of the styling of the input field itself (inlc. paddings/margins), the DateTimePicker, TimePicker should have the same visual as the Input. Because all these components are form components and potentially will be use together and differences in the layout will cause alignment issues.
> 
> If these margins are required (after checking the visual specs) you need to move them from the inner ui5-input to the ui5-(date)time-picker host.

Hello,

After a check with a PO and the visual specs, and we came to the conclusion that the margins should **remain**, but we are moving them to the `ui5-(date)time-picker` host as you said. Thank you!

**Review by Todor-ads — APPROVED** [review]

**Review by ilhan007 — APPROVED** [review]
+1 from my side, build still fails and should pass before merging

**Pull request merged**
