### PR TITLE
fix(ui5-wizard): step titles are now visible

### PR DESCRIPTION
**Pull request by xpr0gamers**
Issue: #3782

### CODE REVIEW

**Review by ilhan007 — APPROVED** [review]
I think the change is fine, we renamed the "heading" prop to "titleText' in the past and this should have been also updated

 @fifoosid could you confirm I think this is related to the PR:
 https://github.com/SAP/ui5-webcomponents/pull/3334

**Review by ilhan007 — DISMISSED** [review]
I am removing my +1, as the component owners @MapTo0 @niyap should approve

**Review by fifoosid — COMMENTED** [review]
LGTM, someone from @SAP/ui5-webcomponents-topic-rl should approve and we can merge it

**Review by niyap — APPROVED** [review]
Looks good for me. Thank you :)

**Review by fifoosid — APPROVED** [review]

**Comment by niyap** [comment]
FIXES: #3782

**Pull request merged**
