### PR TITLE
fix(ui5-select): scroll item into view on keyboard navigation

### PR DESCRIPTION
**Pull request by kgogov**
Fixes: #7164

### CODE REVIEW

**Comment by MapTo0** [comment]
Hello Colleagues, any progress with that?

**Comment by kgogov** [comment]
Hi @MapTo0, It is ready for review. Sorry for the delay..

**Review by PetyaMarkovaBogdanova — APPROVED** [review]

**Comment by ilhan007** [comment]
@kgogov, I am writting this just in case:
did you check if this works with Select + SelectMenu or at least not breaking it.

**Comment by kgogov** [comment]
@ilhan007

I apologize for not having examined this specific scenario, and I acknowledge the concern you've raised. It appears that there is an issue with keyboard navigation when using the Select with the menu property enabled. It's important to note that this problem exists both with and without the changes I made.

**Comment by kgogov** [comment]
@ilhan007 

I apologize for not having examined this specific scenario, and I acknowledge the concern you've raised.
It appears that there is an issue with the keyboard navigation when using the Select with the menu property configured.

It's important to note that this problem exists both with and without the changes I made.

**Pull request merged**
